import json
import os

def update_baseline():
    path = "notebooks/02_baseline_modeling.ipynb"
    print(f"Loading {path}...")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    cell = data["cells"][7]
    assert "def get_model" in "".join(cell["source"])
    
    # We replace get_model implementation to read best_hyperparameters.json, and preserve train_cv
    cell["source"] = [
        "def get_model(model_name: str, seed: int = 42):\n",
        "    \"\"\"Initializes the classifier model using tuned hyperparameters if available.\n",
        "    \"\"\"\n",
        "    # Check for tuned hyperparameters JSON\n",
        "    params_path = 'best_hyperparameters.json'\n",
        "    if not os.path.exists(params_path):\n",
        "        # fallback for Kaggle inputs folder\n",
        "        params_path = '/kaggle/input/stellar-classification-hyperparameter-tuning/best_hyperparameters.json'\n",
        "        if not os.path.exists(params_path):\n",
        "            params_path = '../scratch/best_hyperparameters.json'\n",
        "            \n",
        "    tuned_params = {}\n",
        "    if os.path.exists(params_path):\n",
        "        try:\n",
        "            with open(params_path, 'r') as f:\n",
        "                tuned_params = json.load(f)\n",
        "            print(f\"Loaded tuned hyperparameters from {params_path}!\")\n",
        "        except Exception as e:\n",
        "            print(f\"Error loading tuned parameters: {e}\")\n",
        "            \n",
        "    if model_name == 'lgb':\n",
        "        p = tuned_params.get('lgb', {})\n",
        "        return lgb.LGBMClassifier(\n",
        "            n_estimators=1000,\n",
        "            learning_rate=p.get('learning_rate', 0.05),\n",
        "            num_leaves=p.get('num_leaves', 63),\n",
        "            max_depth=p.get('max_depth', 8),\n",
        "            subsample=p.get('subsample', 0.8),\n",
        "            colsample_bytree=p.get('colsample_bytree', 0.8),\n",
        "            reg_alpha=p.get('reg_alpha', 1e-8),\n",
        "            reg_lambda=p.get('reg_lambda', 1e-8),\n",
        "            class_weight='balanced',\n",
        "            random_state=seed,\n",
        "            n_jobs=-1,\n",
        "            verbose=-1\n",
        "        )\n",
        "    elif model_name == 'xgb':\n",
        "        p = tuned_params.get('xgb', {})\n",
        "        return xgb.XGBClassifier(\n",
        "            n_estimators=1000,\n",
        "            learning_rate=p.get('learning_rate', 0.05),\n",
        "            max_depth=p.get('max_depth', 7),\n",
        "            subsample=p.get('subsample', 0.8),\n",
        "            colsample_bytree=p.get('colsample_bytree', 0.8),\n",
        "            reg_alpha=p.get('reg_alpha', 1e-8),\n",
        "            reg_lambda=p.get('reg_lambda', 1e-8),\n",
        "            tree_method='hist',\n",
        "            random_state=seed,\n",
        "            n_jobs=-1\n",
        "        )\n",
        "    elif model_name == 'cat':\n",
        "        p = tuned_params.get('cat', {})\n",
        "        return CatBoostClassifier(\n",
        "            iterations=1000,\n",
        "            learning_rate=p.get('learning_rate', 0.05),\n",
        "            depth=p.get('depth', 7),\n",
        "            l2_leaf_reg=p.get('l2_leaf_reg', 3.0),\n",
        "            random_strength=p.get('random_strength', 1e-9),\n",
        "            auto_class_weights='Balanced',\n",
        "            random_state=seed,\n",
        "            thread_count=-1,\n",
        "            verbose=False\n",
        "        )\n",
        "    else:\n",
        "        raise ValueError(f\"Unknown model: {model_name}\")\n",
        "\n",
        "def train_cv(model_name: str, n_splits: int = 5, seed: int = 42) -> tuple[np.ndarray, np.ndarray, float]:\n",
        "    \"\"\"Trains a model using Stratified K-Fold CV.\n",
        "    \"\"\"\n",
        "    print(f\"\\nTraining {model_name.upper()} model using {n_splits}-fold Stratified CV...\")\n",
        "    \n",
        "    # Use globally loaded/augmented datasets\n",
        "    global train_raw_global, test_raw_global\n",
        "    train_raw = train_raw_global\n",
        "    test_raw = test_raw_global\n",
        "    \n",
        "    # Preprocess features\n",
        "    X = feature_engineering(train_raw)\n",
        "    y = X.pop('class').map(TARGET_MAP)\n",
        "    X_test = feature_engineering(test_raw)\n",
        "    \n",
        "    print(f\"Feature columns: {list(X.columns)}\")\n",
        "    print(f\"Training shape: {X.shape}, Test shape: {X_test.shape}\")\n",
        "    \n",
        "    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)\n",
        "    \n",
        "    oof_preds = np.zeros((len(X), 3))\n",
        "    test_preds = np.zeros((len(X_test), 3))\n",
        "    fold_scores = []\n",
        "    \n",
        "    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):\n",
        "        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]\n",
        "        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]\n",
        "        \n",
        "        model = get_model(model_name, seed)\n",
        "        \n",
        "        if model_name == 'lgb':\n",
        "            model.fit(\n",
        "                X_train, y_train,\n",
        "                eval_set=[(X_val, y_val)],\n",
        "                callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]\n",
        "            )\n",
        "        elif model_name == 'xgb':\n",
        "            sample_weight = compute_sample_weight('balanced', y_train)\n",
        "            model.fit(\n",
        "                X_train, y_train,\n",
        "                sample_weight=sample_weight,\n",
        "                eval_set=[(X_val, y_val)],\n",
        "                verbose=False\n",
        "            )\n",
        "        elif model_name == 'cat':\n",
        "            model.fit(\n",
        "                X_train, y_train,\n",
        "                eval_set=(X_val, y_val),\n",
        "                early_stopping_rounds=50,\n",
        "                verbose=False\n",
        "            )\n",
        "            \n",
        "        # Predict validation probabilities\n",
        "        val_preds_prob = model.predict_proba(X_val)\n",
        "        oof_preds[val_idx] = val_preds_prob\n",
        "        \n",
        "        # Score fold\n",
        "        val_preds = np.argmax(val_preds_prob, axis=1)\n",
        "        score = balanced_accuracy_score(y_val, val_preds)\n",
        "        fold_scores.append(score)\n",
        "        print(f\"Fold {fold+1} Balanced Accuracy: {score:.5f}\")\n",
        "        \n",
        "        # Test predictions accumulation\n",
        "        test_preds += model.predict_proba(X_test) / n_splits\n",
        "        \n",
        "    cv_score = balanced_accuracy_score(y, np.argmax(oof_preds, axis=1))\n",
        "    print(f\"\\n{model_name.upper()} CV Balanced Accuracy Score: {cv_score:.5f}\")\n",
        "    \n",
        "    # Save out prediction probabilities for blending\n",
        "    os.makedirs(PRED_DIR, exist_ok=True)\n",
        "    np.save(os.path.join(PRED_DIR, f'{model_name}_oof.npy'), oof_preds)\n",
        "    np.save(os.path.join(PRED_DIR, f'{model_name}_test.npy'), test_preds)\n",
        "    \n",
        "    return oof_preds, test_preds, cv_score"
    ]
    
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1)
    print(f"Successfully integrated tuned parameters into {path}!")

if __name__ == "__main__":
    update_baseline()
